name: Build NextWM

on: [push, pull_request]
jobs:
    build:
        name: "Build NextWM"
        runs-on: ubuntu-latest
        container:
            image: archlinux
        steps:
            - name: Get required pacman pkgs
              run: |
                  sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
                  pacman --noconfirm --noprogressbar -Syyu
                  pacman --noconfirm --noprogressbar -Sy wlroots wayland wayland-protocols xorg-xwayland zig make git pkgconf scdoc clang rustup
                  rustup install stable
                  rustup default stable

            - name: Checkout NextWM
              uses: actions/checkout@v2
              with:
                  submodules: true

            - name: Build NextWM
              run: |
                  make

            - name: Build NextWM with Nextctl-rs
              run: |
                  zig build -Dnextctl-rs

            - name: Formatting Check
              run: |
                  make check
