name: Build NextWM

on: [push, pull_request]
jobs:
    build:
        name: "Build NextWM"
        runs-on: ubuntu-latest
        container:
            image: archlinux
        steps:
            - name: Get required pacman pkgs
              run: |
                  sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
                  pacman --noconfirm --noprogressbar -Syyu
                  pacman --noconfirm --noprogressbar -Sy wlroots wayland wayland-protocols xorg-xwayland zig make git pkgconf

            - name: Checkout NextWM
              uses: actions/checkout@v2

            - name: Build NextWM
              run: |
                  git config --global --add safe.directory /__w/NextWM/NextWM
                  git submodule sync --recursive && git submodule update --init --force --recursive
                  make

    documentation:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Check documentation
              run: |
                  sudo apt update
                  sudo apt install --no-install-recommends scdoc
                  for file in $(find . -type f -iname "*.scd"); do scdoc < $file > /dev/null; done
