name: Build NextWM

on: [push, pull_request]
jobs:
    build:
        name: "Build NextWM"
        runs-on: ubuntu-latest
        container:
            image: archlinux
        steps:
            - name: Get required pacman pkgs
              run: |
                  sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel    = Optional TrustAll/' /etc/pacman.conf
                  pacman --noconfirm --noprogressbar -Syyu
                  pacman --noconfirm --noprogressbar -Sy wlroots wayland wayland-protocols xorg-xwayland zig make git pkgconf scdoc

            - name: Checkout NextWM
              uses: actions/checkout@v2

            - name: Formatting Check
              run: |
                  git config --global --add safe.directory /__w/NextWM/NextWM
                  git submodule sync --recursive && git submodule update --init --force --recursive
                  make check

            - name: Build NextWM
              run: |
                  make
