name: Build NextWM (nix)

on: [push, pull_request]
jobs:
    nix:
        name: "Build NextWM"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout NextWM
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: install nix
              uses: cachix/install-nix-action@v20
              with:
                  install_url: https://nixos.org/nix/install
                  extra_nix_config: |
                      auto-optimise-store = true
                      access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
                      experimental-features = nix-command flakes
            - uses: cachix/cachix-action@v12
              with:
                  name: nextwm
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: Build NextWM
              run: |
                  nix develop --command make

            - name: Build NextWM-Xwayland
              run: |
                  nix develop --command 'make BUILD_FLAGS="-Dxwayland -Dxwayland-lazy"'

            - name: Build Nextctl-rs
              run: |
                  nix develop --command 'make -C ./nextctl-rs'

            - name: Build Nextctl-go
              run: |
                  nix develop --command 'make BUILD_FLAGS="-buildvcs=false" -C ./nextctl-go'

            - name: Formatting Check
              run: |
                  nix develop --command 'make check'
